DROP INDEX IF EXISTS apps_slug_key;
ALTER TABLE apps DROP COLUMN IF EXISTS failed_step;
ALTER TABLE apps DROP COLUMN IF EXISTS archive_key;
ALTER TABLE apps DROP COLUMN IF EXISTS port;
ALTER TABLE apps DROP COLUMN IF EXISTS slug;
