ALTER TABLE apps ADD COLUMN IF NOT EXISTS slug TEXT NOT NULL DEFAULT '';
ALTER TABLE apps ADD COLUMN IF NOT EXISTS port INT NOT NULL DEFAULT 8080;
ALTER TABLE apps ADD COLUMN IF NOT EXISTS archive_key TEXT NOT NULL DEFAULT '';
ALTER TABLE apps ADD COLUMN IF NOT EXISTS failed_step TEXT NOT NULL DEFAULT '';
CREATE UNIQUE INDEX IF NOT EXISTS apps_slug_key ON apps(slug) WHERE slug <> '';
