apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: agni-api
  namespace: agni
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - agni.dev
    secretName: agni-api-tls
  rules:
  - host: agni.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: agni-api
            port:
              number: 8080
